### PR TITLE
French translation

### PR DESCRIPTION
**Pull request by lutinotmalin**
Hey !

It's been a while but the partial French translation for Unit Converter is finally here !

Could you please merge the two files and update the SFOS app on OpenRepos ?

Thanks a lot !!!

### CODE REVIEW

**Comment by a-dekker** [comment]
You've overwritten the existing Dutch, but that can be restored :)

**Comment by lutinotmalin** [comment]
Oh wow really ? Sh*t lol, sorry for my mistake. Great it can be restored...

**Comment by a-dekker** [comment]
I'll guess you renamed it. But it's git, so every change is recorded and can be reverted.

**Comment by a-dekker** [comment]
P.s. new version in openrepos.net.

**Pull request merged**
